baseURL = "https://smccall.com/"
languageCode = "en-us"
title = "Sam McCall"

# Google Analytics
# googleAnalytics = " "



# Theme from https://themes.gohugo.io/onepress/
theme = "hago"

DefaultContentLanguage = "en"
metaDataFormat = "yaml"
# disqusShortname = "YOUR_DISQUS_SHORT_NAME"
# googleAnalytics = "UA-XXXXXXXXX-X"
paginate = 4


[Params]
  description = "Sam McCall: Developer, Human, Not a Spy"
  subtitle = "YOUR_SUB_TITLE"
  logo = "/images/logo.png"
  favicon = "/favicon.ico"
  comments = true

[Author]
  name = "Sam"
  website = "https://smccall.com"
