baseURL = "https://smccall.com/"
languageCode = "en-us"
title = "Sam McCall"

# Google Analytics
# googleAnalytics = " "



# Theme from https://themes.gohugo.io/onepress/
theme = "onepress"

# Disable comments by leaving disqusShortname empty
disqusShortname = ""

copyright = "Copyright © 2020, Sam McCall"

[params]
  author = "Sam Mccall"
  bio = "Developer"
  # logo = "images/path/to/image"
  # avatar = "images/path/to/avatar"
  # opengraphImage = "images/path/to/avatar"
  enableRSS = true

  customCSS = false # What does this mean?
  readMore = "Read More..."

  # Socials
  github = "https://github.com/scmccall/"
  linkedin = "https://www.linkedin.com/in/sammccall/"

  widgets = true

  # Author box and Share button
  authorCard = false
  shareButton = false

[taxonomies]
  tag = "tags"